name: Code Quality

on: [push]
env: 
  std_python_version: 3.7

jobs:
  flake8:
    name: "Flake8 stylecheck"
    runs-on: [ubuntu-latest]
    steps:
      - name: Install flake8
        run: pip3 install flake8
      - name: Syntax check
        # stop the build if there are Python syntax errors or undefined names
        run: python3 -m flake8 --count --select=E9,F63,F7,F82 --show-source --statistics command tests
      - name: Style check
        # exit-zero treats all errors as warnings.
        run: python3 -m flake8 --count --exit-zero --max-complexity=10 --max-line-length=100 --statistics command tests
        
  pylint:
    name: "Pylint"
    runs-on: [ubuntu-latest]
    steps:
      - name: Install pylint
        run: pip3 install pylint
      - name: Code analysis
        # stop the build if there are Python syntax errors or undefined names
        run: python3 -m pylint command
          
  # Add Radon, black, mypy? (see https://realpython.com/python-code-quality/)
  test:
    name: Test

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7]

    steps:
    - name: "Git checkout"
      uses: actions/checkout@v1
      
#     - name: Set up Python ${{ matrix.python-version }}
#       uses: actions/setup-python@v1
#       with:
#         python-version: ${{ matrix.python-version }}

    - name: Install dependencies with pipenv
      uses: VaultVulp/action-pipenv@master
      with:
        args: install --dev
    
    - name: Run tests
      uses: VaultVulp/action-pipenv@master
      with:
        args: run pytest tests

